name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
        env:
          TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
          TURSO_DB_AUTH_TOKEN_R: ${{ secrets.TURSO_DB_AUTH_TOKEN_R }}
          TURSO_DB_AUTH_TOKEN_RW: ${{ secrets.TURSO_DB_AUTH_TOKEN_RW }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: Start server
        run: npm run server
